name: redis

instance_groups:
- name: redis
  azs: [z1]
  instances: 2
  vm_type: medium_t
  stemcell: default
  persistent_disk_type: 10GB
  networks: [{name: private}]
  jobs:
  - name: redis
    release: redis
    properties:
      password: ((redis-password))
- name: sanity-tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: medium_t
  stemcell: default
  persistent_disk_type: 10GB
  networks: [{name: private}]
  jobs:
  - name: sanity-tests
    release: redis

variables:
- name: redis-password
  type: password

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent 
  version: 3431.10

releases:
- name: redis
  version: 13.0.0
  url: https://github.com/cloudfoundry-community/redis-boshrelease/releases/download/v13.0.0/redis-13.0.0.tgz
  sha1: 7cc104e398c7c7dc74841343e1a6b689927f7d99
