---
jobs:
- name: job-deploy
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
    - get: resource-bosh-release-redis
    - get: redis-concourse 
  - task: update-cloud-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: amuessig/concourse-bosh}
      params:
        BOSH_ENVIRONMENT: {{bosh-director}}
        BOSH_CA_CERT: {{bosh-cert}}
        BOSH_CLIENT: {{bosh-username}}
        BOSH_CLIENT_SECRET: {{bosh-password}}
        CLOUD_CONFIG: ./cloud-config.yml
      inputs:
        - name: redis-concourse
      run:
        path: sh
        args: 
        - -exc
        - |
          bosh -n cloud-config > $CLOUD_CONFIG
          bosh -n update-cloud-config $CLOUD_CONFIG --ops-file redis-concourse/add-sg.yml -v redis_sg={{redis-sg}}

  - put: resource-redis-bosh-deployment
    params:
      manifest: redis-concourse/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

resources:
- name: redis-concourse
  type: git
  source: 
    uri: https://github.com/eljuanchosf/redis-boshrelease-concourse
    branch: master

- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}
    version_family: {{bosh-stemcell-version}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/redis-boshrelease

- name: resource-redis-bosh-deployment
  type: bosh-deployment
  source:
    target: {{bosh-director}}
    client: {{bosh-username}}
    client_secret: {{bosh-password}}
    ca_cert: {{bosh-cert}}
    deployment: {{redis-deployment-name}} 

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
